pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            agen {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
               dir ('bugtracker-backend'){
                sh 'go test -v  ./...'
               }
            }
        }
    }
}
